name: balance_bot_controller
description: "Flutter app to control Balance Bot with PID tuning capabilities"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.32.7
  shared_preferences: ^2.2.2
  http: ^1.2.1
  flutter_svg: ^1.1.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/design/components/
    - assets/design/screens/

# The following section is used to generate the app icon.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
